### PR TITLE
Trim whitespace for 1D barcode

### PR DESCRIPTION
**Pull request by hardyantz**
remove long whitespace for 1D barcode

### CODE REVIEW

**Comment by boombuler** [comment]
Hi,

I just had a look at it and if I don't miss something your code generates barcodes with the wrong sizes.
If I have a BC with 10px width and want a 20px version of it your code generates a 22px version...

Could you explain what you tried to achieve?

**Comment by hardyantz** [comment]
Hi,
ohh i missed to check the result. 

so, if I generate the code39 barcode with more than 14 characters. the whitespace is to wide. and if I attach the image to document like pdf or something on the fly, the barcode isn't align with the right/left margin. 
what i'am trying to achieve is, i want to remove the whitespace to just 1 px. so it can align with right/left of the document. 

or is there anyway to remove the wide whitespace for character more than 14. ??

Thanks.

**Comment by boombuler** [comment]
Some sample Code that might do the Job for 1D codes:

```golang
import (
    "github.com/boombuler/barcode"
    "image/color"
    "image"
)

type trimmed1DCode struct {
    bc barcode.Barcode
    offLeft int
    offRight int
}


func (t *trimmed1DCode) Metadata() barcode.Metadata {
    return t.bc.Metadata()
}
func (t *trimmed1DCode) Content() string {
    return t.bc.Content()
}

func (t *trimmed1DCode) At(x, y int) color.Color {
    return bc.At(x + t.offLeft, y)
}

func (t *trimmed1DCode) Bounds() image.Rectangle {
    bounds := t.bc.Bounds()
    return image.Rectangle {
        Min : image.Point{
            X: bounds.Min.X + offLeft,
            Y: bounds.Min.Y,
        },
        Max : image.Point{
            X: bounds.Max.X - offRight,
            Y: bounds.Max.Y,
        },
    }
}

func (t *trimmed1DCode) ColorModel() color.Model {
    return t.bc.ColorModel()
}

func newTrimmedCode(bc barcode.Barcode) barcode.Barcode {
    bounds := bc.Bounds()
    left := 0
    for x := bounds.Min.X; x < bounds.Max.X; x++ {
        if bc.At(x, bounds.Min.Y) == color.White {
            left++
        } else {
            break
        }
    }
    right := 0
    for x := bounds.Max.X-1; x >= bounds.Min.X; x-- {
        if bc.At(x, bounds.Min.Y) == color.White {
            right++
        } else {
            break
        }
    }

    return &trimmed1DCode{bc, left, right}
}
```

This might work but is not tested.
Please let me know if it helps you

**Comment by hardyantz** [comment]
thanks. 
i'll try to figured out for this case. 
your awesome.

**Pull request closed without merging**
